name: Build
on: [push, pull_request]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_BUILD: "cp310-*"
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y cmake libxml2-devel libjpeg-devel libtiff-devel 
            libpng-devel giflib-devel freetype-devel libspiro-devel
            libuninameslist-devel gettext-devel
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
