name: Build
on: [push, pull_request]
jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_BUILD: "cp310-*"
          CIBW_CONTAINER_ENGINE: docker
          CIBW_MANYLINUX_X86_64_IMAGE: python:3.10-slim
          CIBW_ENVIRONMENT: >
            PATH=/usr/local/bin:$PATH
            PYTHON=/usr/local/bin/python3.10
            PYTHON_INCLUDE_DIR=/usr/local/include/python3.10
            PYTHON_LIBRARY=/usr/local/lib/libpython3.10.so
          CIBW_BEFORE_ALL_LINUX: >
            apt-get update && apt-get install -y \
            cmake \
            python3-dev \
            libxml2-dev \
            libjpeg-dev \
            libtiff-dev \
            libpng-dev \
            libgif-dev \
            libfreetype6-dev \
            libspiro-dev \
            libuninameslist-dev \
            gettext

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
